version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 12  
    commands:
      - echo using node 12

  pre_build:
    on-failure: ABORT
    commands:
      - echo start pre-build stage
      - npm install
      - npm run test
    finally:
      - echo OK!
     
artifacts:
  files:
    - package.json
