version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo start
      - sudo apt install npm
      - sudo npm install -g n
      - sudo n 12.13.0
    finally:
      - echo OK!
