version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo start
      - apt-get update
      - apt install npm
      - npm install -g n
      - n 12.13.0
    finally:
      - echo OK!
